# Generated by Django 4.2.16 on 2024-09-28 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
